name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.4' # Убедитесь, что это та версия Go, которую вы используете

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest # Можно указать конкретную версию

      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ secrets.GPG_FINGERPRINT }} # Убедитесь, что вы добавили это в секреты репозитория
        run: goreleaser release --rm-dist
